name: Auto Preprocessing on Dataset Change

on:
  push:
    branches: [ main ]
    paths:
      - 'dataset_raw/**'

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas numpy scikit-learn scipy

      - name: Run automate.py
        run: |
          python automate.py

      - name: Upload preprocessing result
        uses: actions/upload-artifact@v3
        with:
          name: preprocessing-result
          path: preprocessing/loan_preprocessing.csv