name: Auto Preprocessing Pipeline

on:
  push:
    paths:
      - 'loan_raw/**'
      - 'preprocessing/**'

permissions:
  contents: write

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install pandas numpy scikit-learn scipy

      - run: python preprocessing/automate_Ferdian.py

      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add preprocessing/loan_preprocessing/loan_clean.csv
          git commit -m "Auto update dataset" || echo "No changes"
          git push